-- 코드를 작성해주세요
SELECT a.ID, IFNULL(b.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA a
LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS COUNT
        FROM ECOLI_DATA
        GROUP BY PARENT_ID
        HAVING PARENT_ID IS NOT NULL
      ) b
ON a.ID = b.PARENT_ID