WITH RENT_INFO AS (
    SELECT
        H.HISTORY_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
      ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT
    R.HISTORY_ID,
    FLOOR(
        R.DAILY_FEE * R.RENT_DAYS *
        (100 - COALESCE(
            CASE
                WHEN R.RENT_DAYS >= 90 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='90일 이상')
                WHEN R.RENT_DAYS >= 30 THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='30일 이상')
                WHEN R.RENT_DAYS >= 7  THEN (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE='트럭' AND DURATION_TYPE='7일 이상')
                ELSE 0
            END
        )) / 100
    ) AS FEE
FROM RENT_INFO R
ORDER BY FEE DESC, R.HISTORY_ID DESC;
