-- 코드를 입력하세요
SELECT a.CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK a JOIN BOOK_SALES b
ON a.BOOK_ID = b.BOOK_ID
WHERE date_format(b.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY